apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
spec:
  selector:
    matchLabels:
      app: vote-app
  replicas: 2
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
        - name: vote
          image: majetraining/vote:v2
          ports:
            - containerPort: 80
